# Generated by Django 5.0 on 2026-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
