# Generated by Django 5.0 on 2026-01-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student_id',
        ),
        migrations.CreateModel(
            name='Bookrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rent_at', models.IntegerField()),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
        ),
    ]
