# Generated by Django 5.0 on 2026-01-16 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_student_id_bookrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrent',
            name='rent_at',
        ),
        migrations.AddField(
            model_name='bookrent',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrent',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
